apiVersion: v1
kind: Secret
metadata:
  name: ecell-db-secret
  namespace: ecell
type: Opaque
stringData:
  POSTGRES_USER: ecell_user
  POSTGRES_PASSWORD: ecell_secret
  POSTGRES_DB: ecell_db
  DATABASE_URL: postgres://ecell_user:ecell_secret@ecell-db-service:5432/ecell_db
